apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      env:
        - name: "HOST_DB"
          valueFrom:
            configMapKeyRef:
              name: sistema-configmap
              key: HOST_DB
        - name: "DATABASE_DB"
          valueFrom:
            configMapKeyRef:
              name: sistema-configmap
              key: DATABASE_DB
        - name: "USER_DB"
          configMapKeyRef:
            name: sistema-configmap
            key: USER_DB
        - name: "PASS_DB"
          configMapKeyRef:
            name: sistema-configmap
            key: PASS_DB
      ports:
        - containerPort: 80
